export const PROJECTS = [
  {
    id: "lake-portfolio",
    index: "01",
    title: "Lake Portfolio",
    category: "Personal Brand Flow",
    blurb:
      "A kinetic portfolio route built to open at the statement first, then let the contact handoff happen naturally.",
    url: "https://portfilo-lake.vercel.app/",
    accent: "#bcff66",
    glow: "#d4ff85",
    geometry: "sphere",
    scale: 0.82,
  },
  {
    id: "olivora",
    index: "02",
    title: "Olivora Naturals",
    category: "Brand Showcase",
    blurb:
      "A clean product story built for calm presentation, quick loading, and stronger brand perception.",
    url: "https://olivoranaturals.vercel.app/",
    accent: "#ffd684",
    glow: "#ffc76d",
    geometry: "torus",
    scale: 0.9,
  },
  {
    id: "diamond-banquet",
    index: "03",
    title: "Diamond Banquet",
    category: "Hospitality Launch",
    blurb:
      "A real-world venue site designed for conversion with location, inquiry, and trust signals kept immediate.",
    url: "https://diamond-banquet-hall.vercel.app/",
    accent: "#ff9f8e",
    glow: "#ff7c67",
    geometry: "icosahedron",
    scale: 1,
  },
  {
    id: "kl-40",
    index: "04",
    title: "KL-40",
    category: "Experimental Interface",
    blurb:
      "A sharper concept build added as a fourth signal in the field, with a colder tone and a more fractured shape language.",
    url: "https://kl-40-git-main-judahvijai-8414s-projects.vercel.app/",
    accent: "#93d8ff",
    glow: "#dff4ff",
    geometry: "dodecahedron",
    scale: 0.88,
    shards: 5,
  },
];
