export const PROJECTS = [
  {
    id: "lake-portfolio",
    index: "01",
    title: "Lake Portfolio",
    category: "Personal Brand Flow",
    blurb:
      "A kinetic portfolio route built to open at the statement first, then let the contact handoff happen naturally.",
    url: "https://portfilo-lake.vercel.app/",
    accent: "#bcff66",
    glow: "#d4ff85",
    geometry: "sphere",
    scale: 0.46,
    ctaLabel: "Launch live site",
  },
  {
    id: "olivora",
    index: "02",
    title: "Olivora Naturals",
    category: "Brand Showcase",
    blurb:
      "A clean product story built for calm presentation, quick loading, and stronger brand perception.",
    url: "https://olivoranaturals.vercel.app/",
    accent: "#ffd684",
    glow: "#ffc76d",
    geometry: "torus",
    scale: 0.5,
    ctaLabel: "Launch live site",
  },
  {
    id: "diamond-banquet",
    index: "03",
    title: "Diamond Banquet",
    category: "Hospitality Launch",
    blurb:
      "A real-world venue site designed for conversion with location, inquiry, and trust signals kept immediate.",
    url: "https://diamond-banquet-hall.vercel.app/",
    accent: "#ff9f8e",
    glow: "#ff7c67",
    geometry: "icosahedron",
    scale: 0.54,
    ctaLabel: "Launch live site",
  },
  {
    id: "kl-40",
    index: "04",
    title: "KL-40",
    category: "Experimental Interface",
    blurb:
      "A sharper concept build added as a fourth signal in the field, with a colder tone and a more fractured shape language.",
    url: "https://kl-40-git-main-judahvijai-8414s-projects.vercel.app/",
    accent: "#93d8ff",
    glow: "#dff4ff",
    geometry: "dodecahedron",
    scale: 0.48,
    shards: 4,
    ctaLabel: "Launch live site",
  },
  {
    id: "sense-stick",
    index: "05",
    title: "Sense Stick",
    category: "Assistive-Tech Prototype",
    blurb:
      "A mobility-aid concept presented at St. Albert's College Expo, combining ultrasonic sensing, embedded logic, and a more serious assistive-tech direction.",
    url: "https://www.linkedin.com/posts/judahv_proud-to-present-at-st-alberts-college-ugcPost-7348045580318756868-kqXh",
    accent: "#aef7d4",
    glow: "#d9ffef",
    geometry: "sense-stick",
    scale: 0.44,
    ctaLabel: "Open proof post",
  },
];
